backend:
  name: github
  branch: main
  repo: White-eclipse1/Paginaweb
  base_url: "https://jolly-sand-06d352c0f.3.azurestaticapps.net/api"
  auth_endpoint: "auth"

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: test
    label: "Prueba"
    folder: "content/test"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "TÃ­tulo", name: "title", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
