backend:
  name: github
  branch: main
  repo: White-eclipse1/Paginaweb
  base_url: "https://jolly-sand-06d352c0f.3.azurestaticapps.net/api"
  auth_endpoint: "auth"

media_folder: "img/uploads"
public_folder: "/img/uploads"

site_url: "https://jolly-sand-06d352c0f.3.azurestaticapps.net"
display_url: "https://jolly-sand-06d352c0f.3.azurestaticapps.net"

publish_mode: editorial_workflow

collections:
  - name: news
    label: "Noticias"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Imagen principal", name: "thumbnail", widget: "image", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false }
      - { label: "Cuerpo", name: "body", widget: "markdown" }

  - name: jobs
    label: "Ofertas de Trabajo"
    folder: "content/jobs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Puesto", name: "title", widget: "string" }
      - { label: "Ubicación", name: "location", widget: "string", required: false }
      - { label: "Modalidad", name: "modality", widget: "select", options: ["Presencial","Híbrido","Remoto"], default: "Presencial" }
      - { label: "Tipo", name: "type", widget: "select", options: ["Tiempo completo","Medio tiempo","Prácticas"], default: "Tiempo completo" }
      - { label: "Sueldo (opcional)", name: "salary", widget: "string", required: false }
      - { label: "Fecha de publicación", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "Imagen", name: "thumbnail", widget: "image", required: false }
      - { label: "Link para aplicar (opcional)", name: "apply_url", widget: "string", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false }
      - { label: "Descripción", name: "body", widget: "markdown" }
